---
abstract: 'Application server with modules, logs, sessions, api, and more.'
author:
  - 'David Helkowski <cpan@codechild.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ginger
no_index:
  directory:
    - t
requires:
  Carp: 0
  Exporter: 0
  Test::More: 0
  XML::Bare: 0.53
  Class::Core: 0.03
  Term::ANSIColor: 0
  URI::Escape: 0
provides:
  Ginger::Reference
    file: Core.pm
    version: 0.02
  Ginger::Reference::Admin::Default
    file: Core/Admin/Default.pm
    version: 0.02
  Ginger::Reference::Cookie::Manager::Default
    file: Core/Cookie/Manager/Default.pm
    version: 0.02
  Ginger::Reference::Log::Default
    file: Core/Log/Default.pm
    version: 0.02
  Ginger::Reference::Permission::Manager::Default
    file: Core/Permission/Manager/Default.pm
    version: 0.02
  Ginger::Reference::Request::Default
    file: Core/Request/Default.pm
    version: 0.02
  Ginger::Reference::Request::IO::HTTP_Server_Simple
    file: Core/Request/IO/HTTP_Server_Simple.pm
    version: 0.02
  Ginger::Reference::Request::IO::Mongrel2
    file: Core/Request/IO/Mongrel2.pm
    version: 0.02
  Ginger::Reference::Request::Manager::Default
    file: Core/Request/Manager/Default.pm
    version: 0.02
  Ginger::Reference::Router::Default
    file: Core/Router/Default.pm
    version: 0.02
  Ginger::Reference::RPC::IO::Mongrel2
    file: Core/RPC/IO/Mongrel2.pm
    version: 0.02
  Ginger::Reference:Session::Manager::Default
    file: Core/Session/Manager/Default.pm
    version: 0.02
  Ginger::Reference::Shared::HTTP_Server_Simple_Wrapper
    file: Core/Shared/HTTP_Server_Simple_Wrapper.pm
    version: 0.01
version: 0.02
