---
abstract: 'Class to handle simple logical set unions and intersections.'
author:
  - 'David Helkowski <cpan@codechild.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Set-Definition
no_index:
  directory:
    - t
requires:
provides:
version: 0.01
